name: CI Workflow

# Define the event that will trigger the workflow (on push)
on:
  push:
    branches:
      - main  # Run the workflow when pushing to the 'main' branch

# Define the jobs to run in this workflow
jobs:
  build:
    # Specify the environment the job will run in
    runs-on: ubuntu-latest

    # Steps to execute the job
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (modify the version if you're working with something else, e.g., Python or Java)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm test

      # (Optional) Step 5: Build the project
      - name: Build Project
        run: npm run build
